"""Render a genuine Frostfang walk generated by the quadruped engine.

The script reads the existing engine-authored QAE_walk action. It does
not keyframe the wolf by hand, change production assets, or publish.
"""

from pathlib import Path

import bpy
from mathutils import Vector


ENGINE_ROOT = (
    Path.home() / "Documents" / "Roblox" /
    "DungeonMMO_Quadruped_AnimationEngine"
)
SOURCE = ENGINE_ROOT / "working" / "Frostfang_QuadrupedStudio.blend"
OUTPUT = ENGINE_ROOT / "qa" / "Frostfang_Engine_Demo"
FRAMES = tuple(range(1, 61, 3))
FRAME_DURATION_MS = 100
RIG_NAME = "Frostfang_Canine_CompactRig"
ACTION_NAME = "QAE_walk"


def create_camera(scene):
    """Create a side-on review camera focused on Frostfang's real mesh.

    Args:
        scene (bpy.types.Scene): Independent Blender demonstration scene.

    Returns:
        bpy.types.Object: Camera used for each frame of the preview.
    """
    data = bpy.data.cameras.new("Engine_Demo_Side")
    camera = bpy.data.objects.new("Engine_Demo_Side", data)
    scene.collection.objects.link(camera)
    camera.location = (2.35, -0.1, 0.8)
    focus = Vector((-0.08, -0.08, 0.49))
    camera.rotation_euler = (
        focus - camera.location
    ).to_track_quat("-Z", "Y").to_euler()
    camera.data.type = "ORTHO"
    camera.data.ortho_scale = 1.85
    scene.camera = camera
    return camera


def prepare_scene():
    """Read the existing engine clip and configure a simple QA render.

    Args:
        None.

    Returns:
        bpy.types.Scene: Independent scene with real engine action active.
    """
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE))
    rig = bpy.data.objects[RIG_NAME]
    action = bpy.data.actions.get(ACTION_NAME)
    if action is None:
        raise RuntimeError("No engine-generated QAE_walk action found")
    if not rig.animation_data:
        rig.animation_data_create()
    rig.animation_data.action = action
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.display.shading.light = "STUDIO"
    scene.display.shading.color_type = "MATERIAL"
    scene.display.shading.show_shadows = True
    scene.render.resolution_x = 460
    scene.render.resolution_y = 300
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = False
    rig.hide_render = True
    create_camera(scene)
    return scene


def render_engine_frames(scene):
    """Render genuine evaluated source-mesh positions for the engine walk.

    Args:
        scene (bpy.types.Scene): Configured independent Blender scene.

    Returns:
        list[Path]: Ordered image files from the engine animation action.
    """
    OUTPUT.mkdir(parents=True, exist_ok=True)
    paths = []
    for frame in FRAMES:
        scene.frame_set(frame)
        destination = OUTPUT / f"Frostfang_Engine_Walk_{frame:03d}.png"
        scene.render.filepath = str(destination)
        bpy.ops.render.render(write_still=True)
        paths.append(destination)
    return paths


def main():
    """Render actual engine-authored wolf frames for a separate GIF builder.

    Args:
        None.

    Returns:
        None: Saves separate real-mesh PNGs and diagnostic details.
    """
    scene = prepare_scene()
    paths = render_engine_frames(scene)
    print("ENGINE_RENDER_COUNT", len(paths), flush=True)
    print("ENGINE_ACTION", ACTION_NAME, flush=True)
    print("ENGINE_FRAME_DIRECTORY", OUTPUT, flush=True)


if __name__ == "__main__":
    main()
