"""Render a genuine Frostfang walk generated by the quadruped engine.

The script reads the existing engine-authored QAE_walk action. It does
not keyframe the wolf by hand, change production assets, or publish.
"""

from pathlib import Path

import bpy
from mathutils import Vector
from PIL import Image, ImageDraw


ENGINE_ROOT = (
    Path.home() / "Documents" / "Roblox" /
    "DungeonMMO_Quadruped_AnimationEngine"
)
SOURCE = ENGINE_ROOT / "working" / "Frostfang_QuadrupedStudio.blend"
OUTPUT = ENGINE_ROOT / "qa" / "Frostfang_Engine_Demo"
FRAMES = tuple(range(1, 61, 3))
FRAME_DURATION_MS = 100
RIG_NAME = "Frostfang_Canine_CompactRig"
ACTION_NAME = "QAE_walk"


def create_camera(scene):
    """Create a side-on review camera focused on Frostfang's real mesh.

    Args:
        scene (bpy.types.Scene): Independent Blender demonstration scene.

    Returns:
        bpy.types.Object: Camera used for each frame of the preview.
    """
    data = bpy.data.cameras.new("Engine_Demo_Side")
    camera = bpy.data.objects.new("Engine_Demo_Side", data)
    scene.collection.objects.link(camera)
    camera.location = (2.35, -0.1, 0.8)
    focus = Vector((-0.08, -0.08, 0.49))
    camera.rotation_euler = (
        focus - camera.location
    ).to_track_quat("-Z", "Y").to_euler()
    camera.data.type = "ORTHO"
    camera.data.ortho_scale = 1.85
    scene.camera = camera
    return camera


def prepare_scene():
    """Read the existing engine clip and configure a simple QA render.

    Args:
        None.

    Returns:
        bpy.types.Scene: Independent scene with real engine action active.
    """
    bpy.ops.wm.open_mainfile(filepath=str(SOURCE))
    rig = bpy.data.objects[RIG_NAME]
    action = bpy.data.actions.get(ACTION_NAME)
    if action is None:
        raise RuntimeError("No engine-generated QAE_walk action found")
    if not rig.animation_data:
        rig.animation_data_create()
    rig.animation_data.action = action
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.display.shading.light = "STUDIO"
    scene.display.shading.color_type = "MATERIAL"
    scene.display.shading.show_shadows = True
    scene.render.resolution_x = 460
    scene.render.resolution_y = 300
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = False
    rig.hide_render = True
    create_camera(scene)
    return scene


def render_engine_frames(scene):
    """Render genuine evaluated source-mesh positions for the engine walk.

    Args:
        scene (bpy.types.Scene): Configured independent Blender scene.

    Returns:
        list[Path]: Ordered image files from the engine animation action.
    """
    OUTPUT.mkdir(parents=True, exist_ok=True)
    paths = []
    for frame in FRAMES:
        scene.frame_set(frame)
        destination = OUTPUT / f"Frostfang_Engine_Walk_{frame:03d}.png"
        scene.render.filepath = str(destination)
        bpy.ops.render.render(write_still=True)
        paths.append(destination)
    return paths


def load_frame(path):
    """Convert a rendered Blender frame into a labelled preview image.

    Args:
        path (Path): Existing rendered source-mesh PNG.

    Returns:
        Image.Image: Quantized RGB sample ready for GIF playback.
    """
    with Image.open(path) as original:
        frame = original.convert("RGB")
    frame.thumbnail((368, 240))
    draw = ImageDraw.Draw(frame)
    draw.text(
        (7, 7), "FROSTFANG / ENGINE WALK / QA ONLY",
        fill=(255, 255, 255),
    )
    return frame.quantize(colors=48)


def build_preview(paths):
    """Encode and verify a looped GIF from real engine-generated poses.

    Args:
        paths (list[Path]): Ordered actual-mesh render frames.

    Returns:
        tuple: Saved GIF path, encoded frame count and total duration.
    """
    images = [load_frame(path) for path in paths]
    gif_path = OUTPUT / "Frostfang_Engine_Walk_QA.gif"
    images[0].save(
        gif_path,
        save_all=True,
        append_images=images[1:],
        duration=FRAME_DURATION_MS,
        loop=0,
        optimize=True,
        disposal=2,
    )
    with Image.open(gif_path) as saved:
        total_ms = 0
        for index in range(saved.n_frames):
            saved.seek(index)
            total_ms += saved.info.get("duration", 0)
        return gif_path, saved.n_frames, total_ms


def main():
    """Generate an engine-authored wolf animation preview, not a mock-up.

    Args:
        None.

    Returns:
        None: Saves a separate real-mesh GIF and diagnostic details.
    """
    scene = prepare_scene()
    paths = render_engine_frames(scene)
    gif_path, count, duration_ms = build_preview(paths)
    if count < 5 or duration_ms < 1000:
        raise RuntimeError("The generated animation preview is incomplete")
    print("ENGINE_PREVIEW_SAVED", gif_path, flush=True)
    print("ENGINE_ACTION", ACTION_NAME, flush=True)
    print("ENGINE_GIF_FRAMES", count, flush=True)
    print("ENGINE_GIF_DURATION_MS", duration_ms, flush=True)
    print("ENGINE_GIF_BYTES", gif_path.stat().st_size, flush=True)


if __name__ == "__main__":
    main()
